FROM node:14

RUN mkdir -p /usr/src/node-api
WORKDIR /usr/src/node-api
COPY . .

ENV NODE_ENV=production
ENV NODE_APP_CORS_URL=https://institution-erp.azurewebsites.net
ENV PG_CONNSTR=postgres://ztcseirs:CVPGGrSB8E6fbRkju2gavpHSzphMpUnA@drona.db.elephantsql.com:5432/ztcseirs

RUN npm install && npm run build:prod

EXPOSE 8081

CMD [ "npm", "start" ]
